ASP.NET Tasks/SimpleGallery/SimpleGallery/Models/ImageModel.cs
namespace SimpleGallery.Models
{
    public class ImageModel
    {
        public int Id { get; set; }
        public string Url { get; set; }
    }
}

ASP.NET Tasks/SimpleGallery/SimpleGallery/ViewModels/ErrorViewModel.cs
using System;

namespace SimpleGallery.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET Tasks/SimpleGallery/SimpleGallery/ViewModels/GalleryDetailViewModel.cs
namespace SimpleGallery.ViewModels
{
    public class GalleryDetailViewModel
    {
        public int Id { get; set; }
        public string Url { get; set; }
    }
}

ASP.NET Tasks/SimpleGallery/SimpleGallery/ViewModels/GalleryImagesViewModel.cs
using SimpleGallery.Models;
using System.Collections.Generic;

namespace SimpleGallery.ViewModels
{
    public class GalleryImagesViewModel
    {
        public IEnumerable<ImageModel> Images { get; set; }
    }
}

ASP.NET Tasks/SimpleGallery/SimpleGallery/ViewModels/UploadImageViewModel.cs
using Microsoft.AspNetCore.Http;

namespace SimpleGallery.ViewModels
{
    public class UploadImageViewModel
    {
        public IFormFile ImageUpload { get; set; }
    }
}

ASP.NET Tasks/SimpleGallery/SimpleGallery/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleGallery.Context;
using SimpleGallery.Helpers;
using SimpleGallery.Models;
using SimpleGallery.ViewModels;
using System;
using System.Linq;

namespace SimpleGallery.Controllers
{
    public class GalleryController : Controller
    {
        private readonly SimpleGalleryDbContext _context;

        private const int PageSize = 3;

        public GalleryController(SimpleGalleryDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var imageList = new PagedData<ImageModel>();

            imageList.Data = _context.Images.Take(PageSize);
            imageList.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)_context.Images.Count() / PageSize));
            imageList.CurrentPage = 1;

            return View(imageList);
        }

        public IActionResult ImageList(int page)
        {
            var imageList = new PagedData<ImageModel>();

            imageList.Data = _context.Images.Skip(PageSize * (page - 1)).Take(PageSize);
            imageList.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)_context.Images.Count() / PageSize));
            imageList.CurrentPage = page;

            return PartialView(imageList);
        }

        public IActionResult Detail(int id)
        {
            var image = _context.Images.Find(id);

            var model = new GalleryDetailViewModel()
            {
                Id = image.Id,
                Url = image.Url
            };

            return View(model);
        }
    }
}

ASP.NET Tasks/SimpleGallery/SimpleGallery/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SimpleGallery.Models;

namespace SimpleGallery.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET Tasks/SimpleGallery/SimpleGallery/Controllers/UploadImageController.cs
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using SimpleGallery.Context;
using SimpleGallery.Models;
using SimpleGallery.ViewModels;

namespace SimpleGallery.Controllers
{
    public class UploadImageController : Controller
    {
        SimpleGalleryDbContext _context;
        IWebHostEnvironment _appEnvironment;

        public UploadImageController(SimpleGalleryDbContext context, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }

        public IActionResult Upload()
        {
            var model = new UploadImageViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UploadNewImage(UploadImageViewModel image)
        {
            if (image.ImageUpload != null)
            {
                string path = "/images/" + image.ImageUpload.FileName;
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await image.ImageUpload.CopyToAsync(fileStream);
                }

                ImageModel galleryImage = new ImageModel()
                {
                    Url = path
                };

                _context.Images.Add(galleryImage);
                _context.SaveChanges();
            }

            return RedirectToAction("Index", "Gallery");
        }
    }
}

ASP.NET Tasks/SimpleGallery/SimpleGallery/Views/Gallery/Detail.cshtml
@model SimpleGallery.ViewModels.GalleryDetailViewModel

<div class="container body-content">
    <div class="row">
        <div>
            <img src="@Model.Url" />
        </div>
    </div>
    <div class="row controls">
        <a class="btn btn-primary" asp-controller="Gallery" asp-action="Index">
            Back to Gallery
        </a>
    </div>
</div>

ASP.NET Tasks/SimpleGallery/SimpleGallery/Views/Gallery/ImageList.cshtml
@model SimpleGallery.Helpers.PagedData<ImageModel>

<div class="container body-content">
    @for (int i = 1; i <= Model.Data.Count(); i++)
    {
        <div class="mySlides">
            <div class="numbertext">@i / @Model.Data.Count()</div>
            <img src=@Model.Data.ToList()[i - 1].Url style="width:100%">
        </div>
    }

    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>

<div class="container body-content">
    <div class="row">
        @foreach (var image in Model.Data)
        {
            <a asp-controller="Gallery" asp-action="Detail" asp-route-id="@image.Id">
                <div class="gallery-image" style="background-image:url(@image.Url)"></div>
            </a>
        }
    </div>
    <div class="row">
        @for (int i = 1; i <= Model.NumberOfPages; i++)
        {
            if (i == Model.CurrentPage)
            {
                @i
            }
            else
            {
                <a class="page-number" href="javascript:void();">@i</a>
            }
        }
    </div>
</div>

<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        if (n > slides.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = slides.length }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slides[slideIndex - 1].style.display = "block";
    }
</script>

ASP.NET Tasks/SimpleGallery/SimpleGallery/Views/Gallery/Index.cshtml
@model SimpleGallery.Helpers.PagedData<ImageModel>

<script type="text/javascript">
    $().ready(function () {
        $(document).on("click", ".page-number", function () {
            var page = parseInt($(this).html());

            $.ajax({
                url: '@Url.Action("ImageList")',
                data: { "page": page },
                success: function (data) {
                    $("#image-list").html(data);
                }
            });
        });
    });
</script>

<div id="image-list">
    @await Html.PartialAsync("ImageList")
</div>

ASP.NET Tasks/SimpleGallery/SimpleGallery/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP.NET Tasks/SimpleGallery/SimpleGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SimpleGallery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Gallery" asp-action="Index">SimpleGallery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UploadImage" asp-action="Upload">Upload</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ASP.NET Tasks/SimpleGallery/SimpleGallery/Views/UploadImage/Upload.cshtml
<div class="container body-content">
    <div class="row">
        <div>
            <form asp-action="UploadNewImage" asp-controller="UploadImage" method="post" enctype="multipart/form-data">
                <div>
                    <label>Browse for Image</label>
                    <input name="ImageUpload" type="file" class="form-control" />
                </div>
                <div class="submit">
                    <input type="submit" class="btn btn-info" value="Submit" />
                </div>
            </form>
        </div>
    </div>
</div>